### ISSUE TITLE
Hellhounds

### ISSUE THREAD

**Issue by sugar0addict** [GentlemanGnu/ZooKeepR#1]
version 1.3.3
So, upon entering the nether from the overworld spawn portal, several hellhounds began to attack even though I tried to give them coal. So, went back to base & got a mega torch. Which I then went back thru long enough to place torch & left. When I returned some time later, they were still there & attacked. After killing them, I went around doing some digging around. Came back to the portal area, & there were some hellhounds nearby. Not sure if they were there before placing the torch.

**Comment by GentlemanGnu** [comment]
The Mega Torch only blocks new spawns.  Animals that preexist the placing of the torch will continue to exist.  Since we were on the Test Server, I took a look and cleared the foxhounds from the area.  They are no longer a problem.
