### ISSUE TITLE
Grindr Villager Trades Tweak

### ISSUE THREAD

**Issue by Rowanfalar** [GentlemanGnu/ZooKeepR#3]
I was looking at the trade in the Alpha 1.3.4 beta test server. The current trade is 64 ingots for varied amounts of pulverized ore. For example 64 ingots of copper will give you 52 pulverized copper. All the trades are like this. 

My concern is that 64 ingots of anything not copper or iron in the current world gen is really really hard to achieve. Would it be possible to lower the ingot price for the more rare ores (ie. nickel, gold, platinum) to 32 ingots for a range of 18-27 pulverized ore? This way, the Grindr Trader is actually used in early game.

**Comment by GentlemanGnu** [comment]
addressed in 
f661551
 Grinder now trades for 1/4 stacks.
