### ISSUE TITLE
How long do butterflies live?

### ISSUE THREAD

**Issue by Abigai1** [GentlemanGnu/ZooKeepR#5]
![2019-08-16_20 59 38](https://user-images.githubusercontent.com/26982666/63297541-81c3a680-c286-11e9-9c87-c1b6973da49d.png)
![2019-08-19_13 19 46](https://user-images.githubusercontent.com/26982666/63297562-9011c280-c286-11e9-9ac9-07e02dcbc4ab.png)
I captured, name-tagged and released about 16 butterflies into my butterfly house -- one or two might have gotten killed on accident, but now I only have one left. I also have not received any death messages for my named butterflies. 

STRANGE!!

**Comment by GentlemanGnu** [comment]
I don't know how or why your butterflies are despawning.  after discussion with you, i am guessing that these entities just disappear over time and fixing that behaviour is beyond my scope.  I will reduce the cost of these butterflies in the animal store to reflect this.
